***Задание 1***

Вычислите значения выражений:

1. 3 * (2 5 0 6 8 10 6 7 5 7) * 2 * (8 6 7 9 6 6 2 3 2 3) = (6 15 0 18 24 30 18 21 15 21) * (16 12 14 18 12 12 4 6 4 6) = 6 * 16 + 15 * 12 + 7 * 0 + 18 * 18 + 24 * 12 + 30 * 12 + 18 * 4 + 21 * 6 + 15 * 4 + 21 * 6 = 1632

2. 6 * (9 6 7 7 0 1 6 8 1 1) * 5 * (0 2 2 6 7 8 8 3 1 8) = (54 36 42 42 0 6 36 48 6 6) * (0 10 10 30 35 40 40 15 5 40) = 54 * 0 + 36 * 10 + 42 * 10 + 42 * 30 + 0 * 35 + 6 * 40 + 36 * 40 + 48 * 15 + 6 * 5 + 6*40 = 4710
3. (2 5 0 6 8 10 6 7 5 7) * (8 6 7 9 6 6 2 3 2 3) = 2 * 8 + 5 * 6 + 0 * 7 + 6 * 9 + 8 * 6 + 10 * 3 + 6 * 2 + 7 * 3 + 5 * 2 + 7 * 3 = 242


***Задание 2***

Ввод элементов массива поэлементно:

In [ ]:
import numpy as np

def create_2d_arr(m, n):
    arr_2d=[]
    for i in range(m):
        internal_arr = []
        
        for j in range(n):
            internal_arr.append(input('Введи элемент матрицы'))
        arr_2d.append(internal_arr)
    return arr_2d

Ввод элементов массива построчно:

In [ ]:
def arra():
    m  = int(input("Введи число строк матрицы: "))
    arr_2d=[]
    for i in range(m):
        arr_2d.append(input('Введи строку: ').split())
    arr_2d = np.array(arr_2d)
    arr_2d = arr_2d.transpose()
    return arr_2d

In [ ]:
arra()

Введи число строк матрицы: 4
Введи строку: 2 1 7 4
Введи строку: 5 6 7 3
Введи строку: 9 8 2 12
Введи строку: 11 14 15 15


array([['2', '5', '9', '11'],
       ['1', '6', '8', '14'],
       ['7', '7', '2', '15'],
       ['4', '3', '12', '15']], dtype='<U2')

In [ ]:
arra()

Введи число строк матрицы: 2
Введи строку: 3 7 8 3 6
Введи строку: 2 5 9 4 13


array([['3', '2'],
       ['7', '5'],
       ['8', '9'],
       ['3', '4'],
       ['6', '13']], dtype='<U2')

***Задание 3***

In [ ]:
from sympy import *
a1, a2 = symbols('a1, a2')

MSE = 1/4 * ((a1 * 1 + a2 * 2 - 5)**2 + \
             (a1 * 5 + a2 * 3 - 6)**2 + \
             (a1 * 2 + a2 * 4 - 10)**2 + \
             (a1 * 3 + a2 * 7 - 8)**2)
MSE.subs({a1: 0.395, a2: 0.62})

16.8572437500000

In [ ]:
MSE = 1/4 * ((a1 * 1 + a2 * 2 - 5)**2 + \
             (a1 * 5 + a2 * 3 - 6)**2 + \
             (a1 * 2 + a2 * 4 - 10)**2 + \
             (a1 * 3 + a2 * 7 - 8)**2)
MSE.subs({a1: 0.57, a2: 0.62})

14.0867750000000

In [ ]:
MSE.subs({a1: 0.57, a2: 0.91})

8.56082500000000

In [ ]:
MSEa1 = diff(MSE, a1)
MSEa1

19.5*a1 + 23.0*a2 - 39.5

In [ ]:
MSEa2 = diff(MSE, a2)
MSEa2

23.0*a1 + 39.0*a2 - 62.0

In [ ]:
step = 0.01

In [ ]:
# Создаем вектор
point = np.array([0.57, 0.91])
point

array([0.57, 0.91])

In [ ]:
#Вычисляем градиент
grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                    MSEa2.subs({a1: point[0], a2: point[1]})])
grad

array([-7.45500000000000, -13.4000000000000], dtype=object)

In [ ]:
# Умножим градиент на шаг и вычтем из точки. Прлучим следующую точку.
next_point = point - step * grad
next_point

array([0.644550000000000, 1.04400000000000], dtype=object)

In [ ]:
# Посмотрим, уменьшилась ли MSE
MSE.subs({a1: next_point[0], a2: next_point[1]})

6.84354744937500

MSE уменьшилась, но недостаточно. Вычисленная next_point станет point для следующей итерации.



In [ ]:
point = next_point
point

array([0.644550000000000, 1.04400000000000], dtype=object)

In [ ]:
grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                    MSEa2.subs({a1: point[0], a2: point[1]})])
grad

array([-2.91927500000000, -6.45935000000000], dtype=object)

In [ ]:
next_point = point - step * grad
next_point

array([0.673742750000000, 1.10859350000000], dtype=object)

In [ ]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

6.47413334061399

И сделаем еще шаг:

In [ ]:
point = next_point
point

array([0.673742750000000, 1.10859350000000], dtype=object)

In [ ]:
grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                    MSEa2.subs({a1: point[0], a2: point[1]})])
grad

array([-0.864365875000004, -3.26877025000000], dtype=object)

In [ ]:
next_point = point - step * grad
next_point

array([0.682386408750000, 1.14128120250000], dtype=object)

In [ ]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

6.38787584353824

Еще:

In [ ]:
point = next_point
grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                    MSEa2.subs({a1: point[0], a2: point[1]})])
next_point = point - step * grad
MSE.subs({a1: next_point[0], a2: next_point[1]})

6.36167480075008

И еще:

In [ ]:
point = next_point
grad = np.array([MSEa1.subs({a1: point[0], a2: point[1]}), 
                    MSEa2.subs({a1: point[0], a2: point[1]})])
next_point = point - step * grad
MSE.subs({a1: next_point[0], a2: next_point[1]})

6.34873371109374